spring.application.name=reactive-weather-api-fetcher


openweather.weather-api-url=https://openweathermap.org/api/widget/onecall
openweather.weather-search-city=https://openweathermap.org/api/widget/geo
